set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(TARGET_TRIPLE x86_64-elf)
set(CMAKE_C_COMPILER ${TARGET_TRIPLE}-gcc)
set(CMAKE_C_FLAGS "-ffreestanding -mno-red-zone")
set(CMAKE_CXX_COMPILER ${TARGET_TRIPLE}-g++)
set(CMAKE_CXX_FLAGS ${CMAKE_C_FLAGS})
set(CMAKE_ASM_COMPILER nasm)

set(CMAKE_LINKER ${TARGET_TRIPLE}-ld CACHE INTERNAL STRING)
set(CMAKE_OBJCOPY ${TARGET_TRIPLE}-objcopy CACHE INTERNAL STRING)
set(CMAKE_AR ${TARGET_TRIPLE}-ar CACHE INTERNAL STRING)
set(CMAKE_SIZE_UTIL ${TARGET_TRIPLE}-size CACHE INTERNAL STRING)
